# Generated by Django 4.2.1 on 2023-06-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='images/noimage.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
